name: Create PR from develop to main

on:
  workflow_dispatch:
    inputs:
      text:
        type: string
        required: true
        description: 'Version'
jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    env:
      GIT_PR_RELEASE_BRANCH_PRODUCTION: main
      GIT_PR_RELEASE_BRANCH_STAGING: develop
      GIT_PR_RELEASE_MENTION: author
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Set up Ruby
        run: |
          rbenv local 2.7.6
          ruby -v || echo
      - name: git-pr-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_TEMPLATE: './.github/workflows/.git-pr-release-template.erb'
        run: |
          gem install git-pr-release
          rbenv rehash
          git-pr-release || echo "Done."
