name: Update version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version'
jobs:
  updateVersion:
    name: update-version
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       - name: output test
         run: |
          echo ${{ github.event.inputs.version }} > VERSION
       - name: create new branch
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git switch -c update_v${{ VERSION }}
           git push -u origin update_v${{ VERSION }}
       - name: add a commit
         uses: EndBug/add-and-commit@v7
         with:
           branch: update_v${{ VERSION }}
           message: ${{ VERSION }}
           add: app/gradle.properties
       - name: Create pull request
         uses: repo-sync/pull-request@v2
         with:
           source_branch: update_v${{ VERSION }}
           destination_branch: main
           pr_title: ${{ VERSION }}
           github_token: ${{ secrets.GITHUB_TOKEN }}

